apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: mlops
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: mlops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
        - name: POSTGRES_DB
          value: "postgres"
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pvc
      - name: init-script
        configMap:
          name: postgres-init
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: mlops
data:
  init.sql: |
    -- Создаем базы данных для Airflow и MLflow
    CREATE DATABASE airflow_db;
    CREATE DATABASE mlflow_db;
    
    -- Создаем пользователей
    CREATE USER airflow_user WITH PASSWORD 'airflow_pass';
    CREATE USER mlflow_user WITH PASSWORD 'mlflow_pass';
    
    -- Даем права
    GRANT ALL PRIVILEGES ON DATABASE airflow_db TO airflow_user;
    GRANT ALL PRIVILEGES ON DATABASE mlflow_db TO mlflow_user;
    
    -- Назначаем владельцев
    ALTER DATABASE airflow_db OWNER TO airflow_user;
    ALTER DATABASE mlflow_db OWNER TO mlflow_user;
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: mlops
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432