apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
  namespace: mlops
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
  AWS_DEFAULT_REGION: ru-central1
  S3_ENDPOINT: https://storage.yandexcloud.net
  S3_BUCKET: ${BUCKET_NAME}
  AIRFLOW_CONN_S3: aws://${AWS_ACCESS_KEY_ID}:${AWS_SECRET_ACCESS_KEY}@?endpoint_url=https%3A%2F%2Fstorage.yandexcloud.net&region_name=ru-central1
